[application]

name = "Cybermap"

[web.wasm_opt]
# The level wasm-opt should target. z is the smallest. 4 is the fastest.
level = "4"

[web.app]

# HTML title tag content
title = "Cybermap"

[bundle]
# Bundle identifier
identifier = "com.bowarc"

# Bundle publisher
publisher = "Bowarc"

# Bundle category
category = "Utility"

# Bundle short description
short_description = "A map in the style of cyberpunk2077"

# Bundle long description
long_description = """
TODO
"""
