[package]
name = "mobile"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "Cybermap"
path = "src/main.rs"

[dependencies]
dioxus = { workspace = true, features = ["router", "mobile"] }
ui = { workspace = true }
osm = { workspace = true }
serde_json.workspace = true
reqwest = { workspace = true, features = ["json", "query"] }
dioxus-sdk-time = "0.7.0"
