[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.26", features = ["json", "stream"] }
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
warp = { version = "0.4.2", features = ["server"] }
warp-rate-limit = { git = "https://github.com/bowarc/warp-rate-limit" }
logger = { git = "https://github.com/bowarc/crates", package = "logger" }
serde = { version = "1.0.228", features = ["derive"] }
log = "0.4.20"
