[package]
name = "web"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = { workspace = true, features = ["router"] }
ui = { workspace = true }
osm = { workspace = true }
serde_json.workspace = true
reqwest = { workspace = true, features = ["json", "query"] }

gloo-timers = "0.3.0"

[features]
default = ["web"]
web = ["dioxus/web"]
